rules:
  "@textlint-rule/no-unmatched-pair": true

  apostrophe: true

  common-misspellings: true

  # en-capitalization:
  #   allowHeading: false
  #   allowLists: true

  stop-words:
    severity: warning

  terminology:
    terms:
      - Stylus
      - VuePress
      - - front[- ]matter
        - frontmatter
    exclude:
      - Node.js
      - URLs
      - repo

    severity: warning

  write-good:
    passive: false
    severity: warning
    whitelist:
      - daily
      - only
      - multiple
      - validate

  zh-half-and-full-width-bracket:
    bracket: halfWidth

filters:
  allowlist:
    allow:
      - "/@flowstart[\\s\\S]*?@flowend/m"

  comments: true
